version: '3.3'
services:
  opsli-ui:
    build: ./
    restart: always
    container_name: opsli-ui
    image: opsli-ui
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - /var/nginx:/var/data #挂载 Nginx 文件
    ports:
      - "80:80"
