import request from "@/utils/request";
const data = [{
  "id": "1",
  "parentId": "0",
  "order": 1,
  "redirect": "index",
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/",
  "component": "Layout",
  "meta": {
    "icon": "home",
    "title": "Dashboard"
  },
  "name": "Dashboard",
  "alwaysShow": "0",
  "children": [{
    "id": "1-1",
    "parentId": "1",
    "order": 1,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "index",
    "component": "views/index/index",
    "meta": {
      "icon": "home",
      "title": "Dashboard"
    },
    "name": "Dashboard",
    "alwaysShow": "0"
  }]
}, {
  "id": "1460639200696160257",
  "parentId": "0",
  "order": 2,
  "redirect": null,
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/org",
  "component": "Layout",
  "meta": {
    "icon": "users",
    "title": "组织机构"
  },
  "name": "组织机构",
  "alwaysShow": "1",
  "children": [{
    "id": "1315201380721446914",
    "parentId": "1460639200696160257",
    "order": 5,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "tenant",
    "component": "views/modules/system/tenantManagement/index",
    "meta": {
      "icon": null,
      "title": "租户管理"
    },
    "name": "租户管理",
    "alwaysShow": "0"
  }]
}, {
  "id": "1",
  "parentId": "0",
  "order": 3,
  "redirect": null,
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/system",
  "component": "Layout",
  "meta": {
    "icon": "cog",
    "title": "系统配置"
  },
  "name": "系统配置",
  "alwaysShow": "0",
  "children": [{
    "id": "1312756531833356289",
    "parentId": "1",
    "order": 6,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "dict",
    "component": "views/modules/system/dictManagement/index",
    "meta": {
      "icon": null,
      "title": "字典管理"
    },
    "name": "字典管理",
    "alwaysShow": "0"
  }, {
    "id": "1387633500164599809",
    "parentId": "1",
    "order": 7,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "options",
    "component": "views/modules/system/optionsManagement/index",
    "meta": {
      "icon": "",
      "title": "参数配置"
    },
    "name": "参数配置",
    "alwaysShow": "0"
  }, {
    "id": "1335439751687208961",
    "parentId": "1",
    "order": 8,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "area",
    "component": "views/modules/system/areaManagement/index",
    "meta": {
      "icon": "",
      "title": "地域管理"
    },
    "name": "地域管理",
    "alwaysShow": "0"
  }, {
    "id": "1360233188433977345",
    "parentId": "1",
    "order": 99,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "set",
    "component": "views/modules/system/setManagement/index",
    "meta": {
      "icon": "",
      "title": "系统设置"
    },
    "name": "系统设置",
    "alwaysShow": "0"
  }]
}, {
  "id": "1504776412970254338",
  "parentId": "0",
  "order": 98,
  "redirect": null,
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/log",
  "component": "Layout",
  "meta": {
    "icon": "file-contract",
    "title": "日志监控"
  },
  "name": "日志监控",
  "alwaysShow": "0",
  "children": [{
    "id": "1504779965155655682",
    "parentId": "1504776412970254338",
    "order": 1,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "login-logs",
    "component": "views/modules/system/loginLogsManagement/index",
    "meta": {
      "icon": "",
      "title": "登录日志"
    },
    "name": "登录日志",
    "alwaysShow": "0"
  }, {
    "id": "1314616518671085570",
    "parentId": "1504776412970254338",
    "order": 2,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "logs",
    "component": "views/modules/system/logsManagement/index",
    "meta": {
      "icon": null,
      "title": "操作日志"
    },
    "name": "操作日志",
    "alwaysShow": "0"
  }]
}, {
  "id": "1314610817013919745",
  "parentId": "0",
  "order": 99,
  "redirect": "noRedirect",
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/devops",
  "component": "Layout",
  "meta": {
    "icon": "laptop-code",
    "title": "运维工具"
  },
  "name": "运维工具",
  "alwaysShow": "0",
  "children": [{
    "id": "1351012936860155906",
    "parentId": "1314610817013919745",
    "order": 1,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "sysmonitor",
    "component": "views/modules/system/monitorManagement/index",
    "meta": {
      "icon": "",
      "title": "系统监控"
    },
    "name": "系统监控",
    "alwaysShow": "0"
  }, {
    "id": "1314799744349913090",
    "parentId": "1314610817013919745",
    "order": 3,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "3",
    "path": "http://8.140.114.57:7000/opsli-boot/druid",
    "component": null,
    "meta": {
      "icon": null,
      "title": "数据库监控",
      "target": "_blank"
    },
    "name": "数据库监控",
    "alwaysShow": "0"
  }]
}, {
  "id": "1314068325453574145",
  "parentId": "0",
  "order": 100,
  "redirect": null,
  "parentIds": null,
  "label": null,
  "type": "1",
  "path": "/deve",
  "component": "Layout",
  "meta": {
    "icon": "tools",
    "title": "开发工具"
  },
  "name": "开发工具",
  "alwaysShow": "0",
  "children": [{
    "id": "1397807288445526017",
    "parentId": "1314068325453574145",
    "order": 1,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "generator",
    "component": "EmptyLayout",
    "meta": {
      "icon": "",
      "title": "开发向导"
    },
    "name": "开发向导",
    "alwaysShow": "1",
    "children": [{
      "id": "1327893773049262082",
      "parentId": "1397807288445526017",
      "order": 1,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "creater",
      "component": "views/modules/generator/table/index",
      "meta": {
        "icon": "",
        "title": "代码生成器"
      },
      "name": "代码生成器",
      "alwaysShow": "0"
    }, {
      "id": "1397807399338729473",
      "parentId": "1397807288445526017",
      "order": 2,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "template",
      "component": "views/modules/generator/template/index",
      "meta": {
        "icon": null,
        "title": "代码模板"
      },
      "name": "代码模板",
      "alwaysShow": "0"
    }]
  }, {
    "id": "1314786106243301378",
    "parentId": "1314068325453574145",
    "order": 2,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "3",
    "path": "http://8.140.114.57:7000/opsli-boot/doc.html",
    "component": null,
    "meta": {
      "icon": null,
      "title": "系统接口",
      "target": "_blank"
    },
    "name": "系统接口",
    "alwaysShow": "0"
  }, {
    "id": "1314071137365307394",
    "parentId": "1314068325453574145",
    "order": 3,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "vab",
    "component": "EmptyLayout",
    "meta": {
      "icon": "",
      "title": "组件"
    },
    "name": "组件",
    "alwaysShow": "0",
    "children": [{
      "id": "1314074765178187777",
      "parentId": "1314071137365307394",
      "order": 1,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "3",
      "path": "https://github.com/hiparker/opsli-boot?utm_source=gold_browser_extension",
      "component": null,
      "meta": {
        "icon": null,
        "title": "外链",
        "target": "_blank"
      },
      "name": "外链",
      "alwaysShow": "0"
    }, {
      "id": "1314075128635600897",
      "parentId": "1314071137365307394",
      "order": 2,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "icon",
      "component": "EmptyLayout",
      "meta": {
        "icon": null,
        "title": "图标"
      },
      "name": "图标",
      "alwaysShow": "0",
      "children": [{
        "id": "1314075267769053186",
        "parentId": "1314075128635600897",
        "order": 1,
        "redirect": null,
        "parentIds": null,
        "label": null,
        "type": "1",
        "path": "awesomeIcon",
        "component": "views/vab/icon/index",
        "meta": {
          "icon": null,
          "title": "常规图标"
        },
        "name": "常规图标",
        "alwaysShow": "0",
        "children": null
      }, {
        "id": "1314075542684708865",
        "parentId": "1314075128635600897",
        "order": 2,
        "redirect": null,
        "parentIds": null,
        "label": null,
        "type": "1",
        "path": "remixIcon",
        "component": "views/vab/icon/remixIcon",
        "meta": {
          "icon": null,
          "title": "小清新图标"
        },
        "name": "小清新图标",
        "alwaysShow": "0",
        "children": null
      }, {
        "id": "1314075764852797442",
        "parentId": "1314075128635600897",
        "order": 3,
        "redirect": null,
        "parentIds": null,
        "label": null,
        "type": "1",
        "path": "colorfulIcon",
        "component": "views/vab/icon/colorfulIcon",
        "meta": {
          "icon": null,
          "title": "多彩图标"
        },
        "name": "多彩图标",
        "alwaysShow": "0",
        "children": null
      }]
    }, {
      "id": "1314075970382082050",
      "parentId": "1314071137365307394",
      "order": 3,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "table",
      "component": "EmptyLayout",
      "meta": {
        "icon": null,
        "title": "表格"
      },
      "name": "表格",
      "alwaysShow": "0",
      "children": [{
        "id": "1314076169481498625",
        "parentId": "1314075970382082050",
        "order": 1,
        "redirect": null,
        "parentIds": null,
        "label": null,
        "type": "1",
        "path": "comprehensiveTable",
        "component": "views/vab/table/index",
        "meta": {
          "icon": null,
          "title": "综合表格"
        },
        "name": "综合表格",
        "alwaysShow": "0",
        "children": null
      }, {
        "id": "1314076280542474242",
        "parentId": "1314075970382082050",
        "order": 2,
        "redirect": null,
        "parentIds": null,
        "label": null,
        "type": "1",
        "path": "inlineEditTable",
        "component": "views/vab/table/inlineEditTable",
        "meta": {
          "icon": null,
          "title": "行内编辑"
        },
        "name": "行内编辑",
        "alwaysShow": "0",
        "children": null
      }]
    }, {
      "id": "1314076678317682689",
      "parentId": "1314071137365307394",
      "order": 4,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "map",
      "component": "views/vab/map/index",
      "meta": {
        "icon": null,
        "title": "地图"
      },
      "name": "地图",
      "alwaysShow": "0"
    }, {
      "id": "1314077008057085954",
      "parentId": "1314071137365307394",
      "order": 5,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "websocket",
      "component": "views/vab/webSocket/index",
      "meta": {
        "icon": null,
        "title": "WebSocket"
      },
      "name": "WebSocket",
      "alwaysShow": "0"
    }, {
      "id": "1314077108560998402",
      "parentId": "1314071137365307394",
      "order": 6,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "form",
      "component": "views/vab/form/index",
      "meta": {
        "icon": null,
        "title": "表单"
      },
      "name": "表单",
      "alwaysShow": "0"
    }, {
      "id": "1314077229235318786",
      "parentId": "1314071137365307394",
      "order": 7,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "element",
      "component": "views/vab/element/index",
      "meta": {
        "icon": null,
        "title": "常用组件"
      },
      "name": "常用组件",
      "alwaysShow": "0"
    }, {
      "id": "1314077399507283970",
      "parentId": "1314071137365307394",
      "order": 8,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "tree",
      "component": "views/vab/tree/index",
      "meta": {
        "icon": null,
        "title": "树"
      },
      "name": "树",
      "alwaysShow": "0"
    }, {
      "id": "1314077518340304897",
      "parentId": "1314071137365307394",
      "order": 9,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "card",
      "component": "views/vab/card/index",
      "meta": {
        "icon": null,
        "title": "卡片"
      },
      "name": "卡片",
      "alwaysShow": "0"
    }, {
      "id": "1314077631905280001",
      "parentId": "1314071137365307394",
      "order": 10,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "betterscroll",
      "component": "views/vab/betterScroll/index",
      "meta": {
        "icon": null,
        "title": "滚动侦测"
      },
      "name": "滚动侦测",
      "alwaysShow": "0"
    }, {
      "id": "1314077729003417602",
      "parentId": "1314071137365307394",
      "order": 11,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "verify",
      "component": "views/vab/verify/index",
      "meta": {
        "icon": null,
        "title": "验证码"
      },
      "name": "验证码",
      "alwaysShow": "0"
    }, {
      "id": "1314120834868060162",
      "parentId": "1314071137365307394",
      "order": 12,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "magnifier",
      "component": "views/vab/magnifier/index",
      "meta": {
        "icon": null,
        "title": "放大镜"
      },
      "name": "放大镜",
      "alwaysShow": "0"
    }, {
      "id": "1314121004749955073",
      "parentId": "1314071137365307394",
      "order": 13,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "echarts",
      "component": "views/vab/echarts/index",
      "meta": {
        "icon": null,
        "title": "图表"
      },
      "name": "图表",
      "alwaysShow": "0"
    }, {
      "id": "1314121200103858178",
      "parentId": "1314071137365307394",
      "order": 14,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "loading",
      "component": "views/vab/loading/index",
      "meta": {
        "icon": null,
        "title": "Loading"
      },
      "name": "Loading",
      "alwaysShow": "0"
    }, {
      "id": "1314121675192672257",
      "parentId": "1314071137365307394",
      "order": 15,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "player",
      "component": "views/vab/player/index",
      "meta": {
        "icon": null,
        "title": "视频播放器"
      },
      "name": "视频播放器",
      "alwaysShow": "0"
    }, {
      "id": "1314121808793837570",
      "parentId": "1314071137365307394",
      "order": 16,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "markdownEditor",
      "component": "views/vab/markdownEditor/index",
      "meta": {
        "icon": null,
        "title": "Markdown编辑器"
      },
      "name": "Markdown编辑器",
      "alwaysShow": "0"
    }, {
      "id": "1314121928784486402",
      "parentId": "1314071137365307394",
      "order": 17,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "editor",
      "component": "views/vab/editor/index",
      "meta": {
        "icon": null,
        "title": "富文本编辑器"
      },
      "name": "富文本编辑器",
      "alwaysShow": "0"
    }, {
      "id": "1314122020136427521",
      "parentId": "1314071137365307394",
      "order": 18,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "qrCode",
      "component": "views/vab/qrCode/index",
      "meta": {
        "icon": null,
        "title": "二维码"
      },
      "name": "二维码",
      "alwaysShow": "0"
    }, {
      "id": "1314122353273217025",
      "parentId": "1314071137365307394",
      "order": 19,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "imgComparison",
      "component": "views/vab/imgComparison/index",
      "meta": {
        "icon": null,
        "title": "图像拖拽比对"
      },
      "name": "图像拖拽比对",
      "alwaysShow": "0"
    }, {
      "id": "1314122123047870466",
      "parentId": "1314071137365307394",
      "order": 20,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "backToTop",
      "component": "views/vab/backToTop/index",
      "meta": {
        "icon": null,
        "title": "返回顶部"
      },
      "name": "返回顶部",
      "alwaysShow": "0"
    }, {
      "id": "1314122457908518914",
      "parentId": "1314071137365307394",
      "order": 21,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "codeGenerator",
      "component": "views/vab/codeGenerator/index",
      "meta": {
        "icon": null,
        "title": "代码生成机"
      },
      "name": "代码生成机",
      "alwaysShow": "0"
    }, {
      "id": "1314122556776652802",
      "parentId": "1314071137365307394",
      "order": 22,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "markdown",
      "component": "views/vab/markdown/index",
      "meta": {
        "icon": null,
        "title": "markdown阅读器"
      },
      "name": "markdown阅读器",
      "alwaysShow": "0"
    }, {
      "id": "1314122628184678401",
      "parentId": "1314071137365307394",
      "order": 23,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "smallComponents",
      "component": "views/vab/smallComponents/index",
      "meta": {
        "icon": null,
        "title": "小组件"
      },
      "name": "小组件",
      "alwaysShow": "0"
    }, {
      "id": "1314122717041008641",
      "parentId": "1314071137365307394",
      "order": 24,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "upload",
      "component": "views/vab/upload/index",
      "meta": {
        "icon": null,
        "title": "上传"
      },
      "name": "上传",
      "alwaysShow": "0"
    }, {
      "id": "1314123071354839041",
      "parentId": "1314071137365307394",
      "order": 25,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "sticky",
      "component": "views/vab/sticky/index",
      "meta": {
        "icon": null,
        "title": "Sticky吸附"
      },
      "name": "Sticky吸附",
      "alwaysShow": "0"
    }, {
      "id": "1314123272790482945",
      "parentId": "1314071137365307394",
      "order": 26,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "errorLog",
      "component": "views/vab/errorLog/index",
      "meta": {
        "icon": null,
        "title": "错误日志模拟"
      },
      "name": "错误日志模拟",
      "alwaysShow": "0"
    }]
  }, {
    "id": "1314123690283114498",
    "parentId": "1314068325453574145",
    "order": 4,
    "redirect": null,
    "parentIds": null,
    "label": null,
    "type": "1",
    "path": "mall",
    "component": "EmptyLayout",
    "meta": {
      "icon": null,
      "title": "商城"
    },
    "name": "商城",
    "alwaysShow": "0",
    "children": [{
      "id": "1314123894637993985",
      "parentId": "1314123690283114498",
      "order": 1,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "pay",
      "component": "views/mall/pay/index",
      "meta": {
        "icon": null,
        "title": "支付"
      },
      "name": "支付",
      "alwaysShow": "0"
    }, {
      "id": "1314123990633029633",
      "parentId": "1314123690283114498",
      "order": 2,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "goodsList",
      "component": "views/mall/goodsList/index",
      "meta": {
        "icon": null,
        "title": "商品列表"
      },
      "name": "商品列表",
      "alwaysShow": "0"
    }, {
      "id": "1314124102365093890",
      "parentId": "1314123690283114498",
      "order": 3,
      "redirect": null,
      "parentIds": null,
      "label": null,
      "type": "1",
      "path": "goodsDetail",
      "component": "views/mall/goodsDetail/index",
      "meta": {
        "icon": null,
        "title": "商品详情"
      },
      "name": "商品详情",
      "alwaysShow": "0"
    }]
  }]
}]



export function getRouterList() {


  return Promise.resolve({
    "success": true,
    "msg": "操作成功！",
    "code": 200,
    "timestamp": 1653899678894,
    data
  })
  return request({
    url: "/api/v1/system/menu/findMenuTree",
    method: "post",
    data,
  });
}
